### ISSUE TITLE
DTC setup doesn't match doco

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus.PowerShell#21]
[Documentation](http://docs.particular.net/nservicebus/transactions-message-processing) specifies that below settings should be enabled to get NSB to work properly
![DTC setup](http://docs.particular.net/nservicebus/dtc-dcomcnfg-3.png)

[DtcSetup.cs](https://github.com/Particular/NServiceBus.PowerShell/blob/develop/src/NServiceBus.PowerShell/Dtc/DtcSetup.cs#L86) enables four settings 

```
"NetworkDtcAccess", "NetworkDtcAccessOutbound", "NetworkDtcAccessTransactions", "XaTransactions"
```

and leaves a lot of the others untouched

What are the correct DTC settings?

**Comment by gbiellem** [comment]
@chrisbednarski  I'm closing this. Feel free to re-open if you want to discuss further
