### ISSUE TITLE
Install-NServiceBusMSMQ cmdlet doesn't install on Windows 10

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus.PowerShell#25]
The Install-NServiceBusMSMQ cmdlet returns OS version isn't supported yet

**Comment by gbiellem** [comment]
Fixed - https://github.com/Particular/NServiceBus.PowerShell/commit/e5fbc510a8db3d37402aa946ea39dc12ea202ade

**Comment by gbiellem** [comment]
Added Windows 10 to the list of supported OSes for this cmdlet.
The underlying DISM command is the same as Windows 8.x

**Comment by gbiellem** [comment]
@chrisbednarski  this patch has been released. Here's the link to to [Installer](https://github.com/Particular/NServiceBus.PowerShell/releases/download/5.0.2/Particular.NServiceBusPowershell-5.0.2.exe) for the 5.0.2 release

**Comment by chrisbednarski** [comment]
Thanks @gbiellem
