### ISSUE TITLE
Fix DTC documentation

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus.PowerShell#33]
Although #27 was reverted, the documetation still mentions the NetworkDtcAccessInbound and NetworkDtcAccessClients registry keys. This is because the documentation was updated in the "wrong" pull request #29

**Comment by gbiellem** [comment]
@cremor the docs was fixed on the 5.1 release but I've only just merged that back to develop
See https://github.com/Particular/NServiceBus.PowerShell/commit/6981e7f37e3fe7c10c825b037428832ccb3321c2

So were you looking develop or are you seeing and issue in the deployed version on 5.1?

**Comment by cremor** [comment]
Oh, yes, sorry, I only checked the develop branch.

**Comment by gbiellem** [comment]
Thanks @cremor
