### ISSUE TITLE
Add feature to InstallPlatformLicense cmdlet to import a license from a string

### ISSUE THREAD

**Issue by LankyPaddy** [Particular/NServiceBus.PowerShell#34]
InstallPlatformLicense cmdlet currently only supports importing a license from a file on the local file system. It would be very useful if it would support importing licenses from a supplied string variable. 

My licenses are stored as Octopus Deploy variables, importing the license as a string saves unnecessary complication of writing the data to disk, importing, then removing the file.

**Comment by gbiellem** [comment]
@LankyPaddy I'll release 5.2 next week. Only change will be your PR.  I need to address #32  to make that happen. Would you like me to ping you after it's released?

**Comment by LankyPaddy** [comment]
@gbiellem Yes please - I'll upgrade our systems once it's released

**Comment by gbiellem** [comment]
@LankyPaddy  It's released - https://github.com/particular/NServiceBus.PowerShell/releases/tag/5.2.0
