### ISSUE TITLE
Silent uninstall

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.PowerShell#39]
I cannot for the life of me get the silent uninstall to work for the NServiceBus powershell tools.  Can someone please provide a working example of the parameters?

**Comment by gbiellem** [comment]
Hi @TraGicCode 

The installation is a standard MSI so you can uninstall it using `msiexec.exe` from a elevated command prompt and passing it the MSI product code as follows:

```cmd
MsiExec.exe /uninstall {49387C26-8329-4738-8951-DC49043E6775}  /qn
```
The product code is version independent.  You can verify the product code using this powershell.
Enumerating through the product list is pretty slow so this will take a couple seconds to run:

```PS
$product = Get-WmiObject -Class Win32_Product | ? Name -match "NServiceBus Powershell"
if ($product) {
    $product.Properties["IdentifyingNumber"].Value
}
```
Or you can do the lot from an elevated Powershell prompt:

```PS
$product = Get-WmiObject -Class Win32_Product | ? Name -match "NServiceBus Powershell"
if ($product) {
    $product.uninstall()
}
```
Uninstall returns an object with a return result.  Typically 0 for success or 1603 for failure.

**Comment by TraGicCode** [comment]
@gbiellem The snippet for uninstallation doesn't work using msiexec.  I'm trying to create a puppet module to install the powershell tools and configure performance counters so this is a bit of pain to try and have some special powershell script for uninstallation.  This doesn't seem ideal.

**Comment by gbiellem** [comment]
Hi @TraGicCode 

> The snippet for uninstallation doesn't work using msiexec. 

I've retested  the msiexec snippet and it works if running in an admin context ( i.e elevated command prompt). If not it silently exits.   If you want to determine why uninstall isn't working  add some logging like this:

```
MsiExec.exe /uninstall {49387C26-8329-4738-8951-DC49043E6775}  /qn /L uninstall.log
```
> I'm trying to create a puppet module to install the powershell tools and configure performance counters so this is a bit of pain to try and have some special powershell script for uninstallation.

Ah in that case don't do an install!
You don't actually need to install the MSI on target machine to use the Powershell Module.
Installing it just unpacks it and adds it to the PSModulePath Environment var.
What you can do instead is just copy the NServiceBus.Powershell.dll  to the target machine and use it directly

```
Import-Module <PathToDLL>
Install-NServiceBusPerformanceCounters
```

Does that help?

**Comment by TraGicCode** [comment]
Yea but the whole workflow is a bit unideal.  In order to get the NServiceBus.Powershell.dll you must run the installer.  Then you if you want to story it in chocolatey you have to write all the needed code for that which essentially does what the installer does

1.) Put dll in certain location
2.) Update module path

Is it possible a chocolatey package can be created for this guy?  Also the nuget package on the nuget gallery is not kept up-to-date from what i saw.  Not sure if someone else is maintaining that.

**Comment by gbiellem** [comment]
@TraGicCode  I see your point 

> Also the nuget package on the nuget gallery is not kept up-to-date from what i saw. Not sure if someone else is maintaining that.

Thanks for the heads up,  TBH I thought it had been unlisted after this repo was created and the installer version made.  I'm not sure if it was deliberately left listed or not, I'll have to ask around

> Is it possible a chocolatey package can be created for this guy? 

AFAIK there's no plans to create a chocolatey package for this.

It's more likely we'll create native PS scripts based on the various function in the DLL and offer them as alternatives.

The idea being anyone can include the script in their deployment method of choice.  We've  started doing that with other aspects of the installation -> https://docs.particular.net/nservicebus/msmq/operations-scripting#create-queues

**Comment by HEskandari** [comment]
@TraGicCode I'm closing this issue as the snippet above allows silent uninstalls if that's really needed. We have [another issue](https://github.com/Particular/NServiceBus.PowerShell/issues/44) to decide to publish it to PowerShell Gallery as another installation medium so you don't have to rely on the installer/.exe files.
