### ISSUE TITLE
Obsolete performance counter cmdlets

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.PowerShell#41]
Relates to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/50

Given that we are automating the creation of the powershell cmdlets when you pull in the msbuild target I think we should start obsoleting the cmdlets and pointing to new performance counter package that is yet to be released. Thoughts @Particular/metrics-maintainers @Particular/platforminstaller-maintainers ?

https://rkeithhill.wordpress.com/2012/04/29/powershell-v3-obsoleteattribute/

// cc @WojcikMike

**Comment by gbiellem** [comment]
FYI.  To use the attribute we'll need to bump the min powershell version that we support.  Currently NSB Powershell targets powershell 2.0 not 3.0

**Comment by danielmarbach** [comment]
@gbiellem would you be willing to join our TF and get this going or do you think we should decouple this work from the https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/50 issue?

**Comment by gbiellem** [comment]
@danielmarbach depends on timing.  I'm out of the office til the 1st,  I already raised a PR for the obsolete message. I assume all we need to do is update any of the  reference in the docs site to make this clear that it;s obsolete and point to the  docs for the new mechanism.  I don't see  a hard dependency on doing this prior to the release of the perf counters package so it would be OK IMO  if this was decoupled

**Comment by danielmarbach** [comment]
Fixed as part of #42
