### ISSUE TITLE
Obsolete NServiceBus DTC powershell

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.PowerShell#45]
When the NserviceBus DTC cmdlets were introduced Microsoft did not provide out of the box configuration for DTC via powershell.  This changed when Windows 8.1/Windows 2012 R2 was released. and now  Microsoft  provide a more comprehensive set of configuration options - https://technet.microsoft.com/en-us/library/dn464259(v=wps.630).aspx

Based on this it would  seem the NServiceBus cmdlet for DTC config should be obsoleted and the documentation updated to reflect using the MS approach

@Particular/nservicebus-maintainers do you agree?

**Comment by timbussmann** [comment]
> Windows 8.1/Windows 2012 R2 was released.

what windows versions are we officially supporting?

**Comment by gbiellem** [comment]
@timbussmann  I don't think that is relevant if we implement this in the same way as the recent perf counter change. We'd only be adding a warning that this is obsolete and to refer to the doco, not removing the cmdlet.  So it would still function as it does today for older OSes,

**Comment by HEskandari** [comment]
Thanks @gbiellem. We will mark this cmdlet as obsolete with a message in the next version.

**Comment by HEskandari** [comment]
Resolved via https://github.com/Particular/NServiceBus.PowerShell/pull/68
