### ISSUE TITLE
Remove the Install-RavenDB cmdlet

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.PowerShell#9]
Also remove the Test-RavenDB commandlet

We'll solve this with documentation and guidance instead.

Relevant docs issue: https://github.com/Particular/docs.particular.net/issues/248

Question should we remove the DTC+Msmq as well and guide them to our chocopackages?

**Comment by gbiellem** [comment]
RavenDB cmdlets have been removed
